[versions]
androidx-experiemental-version = "1.3.1"

[libraries]
androidx-annotation-experimental = { module = "androidx.annotation:annotation-experimental", package = "aar", version.ref = "androidx-experiemental-version" }
